pipeline{
    agent any
    stages {
        stage('Clone Code'){
            steps{
                sh "git clone https://github.com/devopsPRO27/tictactoe.git"
            }
        }
        stage('Scan files'){
            steps{
                sh "ls -la"
            }
        }
        stage('Test'){
            steps{
                sh "pwd"
            }
        }
    }
}